sudo: false  
language: node_js
node_js:
  - "8.10.0"

before_script:
 - npm i
 - wget https://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
 - sudo cp selenium-server-standalone-*.jar ./bin
 - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip -d ./bin
 - cd bin && ls
 #- npm install -g nightwatch

script:
  - 
  - nightwatch tests/mocha.js -e mocha
