sudo: false  
language: node_js
node_js:
  - "8.10.0"

before_script:
 - npm install
 - wget https://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
 - sudo cp selenium-server-standalone-*.jar ./bin
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
 - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C ./bin
 - npm install -g nightwatch

script:
  - 
  - nightwatch tests/mocha.js -e mocha
